# nixpacks.toml for Railway Laravel Hosting

[phases.setup]
nixPkgs = ["php84Modules.bcmath", "php84Modules.gd", "php84Modules.intl", "php84Modules.mbstring", "php84Modules.mysql", "php84Modules.opcache", "php84Modules.pdo_mysql", "php84Modules.xml", "php84Modules.zip"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --ignore-platform-reqs", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
